version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: pyipam
      POSTGRES_PASSWORD: pyipam123
      POSTGRES_DB: pyipamdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: pyipam
      POSTGRES_PASSWORD: pyipam123
      POSTGRES_DB: pyipamdb

volumes:
  postgres-data:
